"""add user table

Revision ID: 99bc1fcc52eb
Revises: 
Create Date: 2026-02-08 15:48:27.570816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99bc1fcc52eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    if "users" not in table_names:
        op.create_table(
            "users",
            sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text("gen_random_uuid()")),
            sa.Column("email", sa.String(length=255), nullable=False),
            sa.Column("first_name", sa.String(length=100), nullable=False),
            sa.Column("last_name", sa.String(length=100), nullable=False),
            sa.Column("password_hash", sa.String(length=255), nullable=False),
            sa.Column("avatar_url", sa.String(length=500), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True, server_default=sa.text("now()")),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("email"),
        )
        op.create_index("ix_users_email", "users", ["email"], unique=False)

    if "profiles" not in table_names:
        op.create_table(
            "profiles",
            sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text("gen_random_uuid()")),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("company", sa.String(length=100), nullable=False),
            sa.Column("role", sa.String(length=100), nullable=False),
            sa.Column("location", sa.String(length=100), nullable=False),
            sa.Column("bio", sa.String(length=500), nullable=True, server_default=sa.text("''::character varying")),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True, server_default=sa.text("now()")),
            sa.PrimaryKeyConstraint("id"),
        )
        op.execute("CREATE INDEX idx_profiles_company ON profiles USING gin(to_tsvector('english', company))")
        op.execute("CREATE INDEX idx_profiles_location ON profiles USING gin(to_tsvector('english', location))")
        op.execute("CREATE INDEX idx_profiles_name ON profiles USING gin(to_tsvector('english', name))")
        op.execute("CREATE INDEX idx_profiles_role ON profiles USING gin(to_tsvector('english', role))")

    if "reviews" not in table_names:
        op.create_table(
            "reviews",
            sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text("gen_random_uuid()")),
            sa.Column("profile_id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column("author", sa.String(length=100), nullable=False),
            sa.Column("rating", sa.Integer(), nullable=False),
            sa.Column("comment", sa.String(length=1000), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True, server_default=sa.text("now()")),
            sa.CheckConstraint("rating >= 1 AND rating <= 5"),
            sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("idx_reviews_profile_id", "reviews", ["profile_id"], unique=False)

    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute("DROP INDEX IF EXISTS idx_profiles_company")
    op.execute("DROP INDEX IF EXISTS idx_profiles_location")
    op.execute("DROP INDEX IF EXISTS idx_profiles_name")
    op.execute("DROP INDEX IF EXISTS idx_profiles_role")
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute("DROP INDEX IF EXISTS idx_reviews_profile_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reviews_profile_id'), 'reviews', ['profile_id'], unique=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_profiles_role'), 'profiles', [sa.literal_column("to_tsvector('english'::regconfig, role::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_profiles_name'), 'profiles', [sa.literal_column("to_tsvector('english'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_profiles_location'), 'profiles', [sa.literal_column("to_tsvector('english'::regconfig, location::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_profiles_company'), 'profiles', [sa.literal_column("to_tsvector('english'::regconfig, company::text)")], unique=False, postgresql_using='gin')
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
