"""add user table

Revision ID: 99bc1fcc52eb
Revises: 
Create Date: 2026-02-08 15:48:27.570816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99bc1fcc52eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_profiles_company'), table_name='profiles', postgresql_using='gin')
    op.drop_index(op.f('idx_profiles_location'), table_name='profiles', postgresql_using='gin')
    op.drop_index(op.f('idx_profiles_name'), table_name='profiles', postgresql_using='gin')
    op.drop_index(op.f('idx_profiles_role'), table_name='profiles', postgresql_using='gin')
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reviews_profile_id'), table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reviews_profile_id'), 'reviews', ['profile_id'], unique=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_profiles_role'), 'profiles', [sa.literal_column("to_tsvector('english'::regconfig, role::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_profiles_name'), 'profiles', [sa.literal_column("to_tsvector('english'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_profiles_location'), 'profiles', [sa.literal_column("to_tsvector('english'::regconfig, location::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_profiles_company'), 'profiles', [sa.literal_column("to_tsvector('english'::regconfig, company::text)")], unique=False, postgresql_using='gin')
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
